### ISSUE TITLE
Error when input type="number"

### ISSUE THREAD

**Issue by nikolas** [KevinSheedy/jquery.alphanum#36] opened 2014-12-09 20:40 UTC
I get this error when using `.numeric()` with an input that has `type="number"`:

> Uncaught InvalidStateError: Failed to read the 'selectionStart' property from 'HTMLInputElement': The input element's type ('number') does not support selection.

**Comment by Mottie** [comment] 2015-01-25 15:52
See #19.

**Comment by KevinSheedy** [comment] 2016-02-16 16:41
Duplicate of #19

**Closed by KevinSheedy** 2016-02-16 16:41 UTC
Labels: duplicate
